### ISSUE TITLE
Script unusable inside discord.

### ISSUE THREAD

**Issue by Godrickharg** [ThePsionic/RSWikiLinker#37]
Clyde
BOT
 — Today at 21:57
Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends. You can see the full list of reasons here: https://support.discord.com/hc/en-gb/articles/360060145013

Please note that wikia is now fandom.com. might need a script update?

**Comment by invalidCards** [comment]
The public instance of the bot has been down since Discord changed domains from discordapp.com to discord.com last year, and I don't intend on updating it any more.
